export default {
    size: {
        extraLargeTitle: 36,
        extraLargeTitle2: 28,
        largeTitle: 34,
        title1: 28,
        title2: 22,
        title3: 20,
        headline: 17,
        subheadline: 15,
        body: 14,
        callout: 16,
        footnote: 13,
        caption1: 11,
        caption2: 10,
    },

    family: {
        "Light-Italic": "Inter-ExtraLightItalic",
        Light: "Inter-ExtraLight",
        "Regular-Italic": "Inter-ThinItalic",
        Regular: "Inter-Regular",
        "Medium-Italic": "nter-Medium",
        Medium: "Inter-Medium",
        "Semibold-Italic": "Inter-SemiBoldItalic",
        Semibold: "Inter-SemiBold",
        "Bold-Italic": "Inter-BlackItalic",
        Bold: "Inter-Bold",
        "Black-Italic": "Inter-ExtraBoldItalic",
        Black: "Inter-ExtraBold",
    },
}
