require File.join(
  File.dirname(`node --print "require.resolve('expo/package.json')"`),
  "scripts/autolinking"
)

require File.join(
  File.dirname(`node --print "require.resolve('react-native/package.json')"`),
  "scripts/react_native_pods"
)

require 'json'

podfile_properties = JSON.parse(
  File.read(File.join(__dir__, 'Podfile.properties.json'))
) rescue {}

platform :ios, '15.1'

install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

target 'CircleApp' do
  # 🔴 IMPORTANTE: precisa ficar DENTRO do target
  use_frameworks! :linkage => :static

  use_expo_modules!

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |build_config|
      build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
    end
  end
end

end
