export default {
    size: {
        extraLargeTitle: 36,
        extraLargeTitle2: 28,
        largeTitle: 34,
        title1: 28,
        title2: 22,
        title3: 20,
        headline: 17,
        subheadline: 15,
        body: 14,
        callout: 16,
        footnote: 13,
        caption1: 11,
        caption2: 10,
    },

    family: {
        "Light-Italic": "SFPRODISPLAYULTRALIGHTITALIC",
        Light: "RaptorV3Premium-Light",
        "Regular-Italic": "RaptorV3Premium-RegularSlanted",
        Regular: "SFPRODISPLAYREGULAR",
        "Medium-Italic": "RedHatDisplay-MediumItalic",
        Medium: "SFPRODISPLAYMEDIUM",
        "Semibold-Italic": "SFPRODISPLAYSEMIBOLDITALIC",
        Semibold: "RaptorV3Premium-Semibold",
        "Bold-Italic": "RedHatDisplay-BoldItalic",
        Bold: "SFPRODISPLAYBOLD",
        "Black-Italic": "SFPRODISPLAYHEAVYITALIC",
        Black: "RaptorV3Premium-Black",
    },
}
